# Generated by Django 5.0 on 2023-12-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school_number', models.IntegerField()),
                ('school_class', models.CharField(max_length=5)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
