# Generated by Django 5.0 on 2023-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('lesson_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Pupils',
            new_name='Pupil',
        ),
    ]
