# Generated by Django 5.0 on 2023-12-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0003_school_school_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_class',
            new_name='SchoolClass',
        ),
    ]
