# Generated by Django 5.0 on 2023-12-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0004_rename_school_class_schoolclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pupils.school'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.pupil'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='class_number',
            field=models.IntegerField(),
        ),
    ]
