# Generated by Django 5.0 on 2023-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0005_lesson_price_schoolclass_school_alter_lesson_pupil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_comment',
            field=models.TextField(default='No comment'),
            preserve_default=False,
        ),
    ]
