# Generated by Django 5.0 on 2023-12-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0006_lesson_lesson_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_comment',
            field=models.TextField(blank=True),
        ),
    ]
